name: saleor_mobile
description: "Saleor e-commerce mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  graphql_flutter: ^5.2.0-beta.7
  graphql: ^5.2.0-beta.7
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
